### ISSUE TITLE
Error while getting account balance.

### ISSUE THREAD

**Issue by hmmmk** [Chainers/Ditch#10]
When i trying to check user balance i get Error with text: `"+		Error	{Ditch.Core.Errors.ResponseError. Code: '1'. Message: '10 assert_exception: Assert Exception
itr != _by_name.end(): no method with name 'get_account_balances'
    {"name":"get_account_balances","api":{"cancel_all_subscriptions":3,"get_account_bandwidth":48,"get_account_count":41,"get_account_history":43,"get_account_references":38,"get_account_votes":61,"get_accounts":37,"get_active_categories":25,"get_active_votes":60,"get_active_witnesses":71,"get_best_categories":24,"get_block":20,"get_block_header":19,"get_chain_properties":30,"get_config":27,"get_content":62,"get_content_replies":63,"get_conversion_requests":42,"get_current_median_history_price":32,"get_discussions_by_active":9,"get_discussions_by_author_before_date":64,"get_discussions_by_blog":16,"get_discussions_by_cashout":10,"get_discussions_by_children":13,"get_discussions_by_comments":17,"get_discussions_by_created":8,"get_discussions_by_feed":15,"get_discussions_by_hot":14,"get_discussions_by_payout":11,"get_discussions_by_promoted":18,"get_discussions_by_trending":6,"get_discussions_by_trending30":7,"get_discussions_by_votes":12,"get_dynamic_global_properties":29,"get_escrow":46,"get_feed_history":31,"get_free_memory":28,"get_hardfork_version":34,"get_key_references":36,"get_liquidity_queue":53,"get_miner_queue":72,"get_next_scheduled_hardfork":35,"get_open_orders":52,"get_ops_in_block":21,"get_order_book":51,"get_owner_history":44,"get_potential_signatures":57,"get_recent_categories":26,"get_recovery_request":45,"get_replies_by_last_update":65,"get_required_signatures":56,"get_savings_withdraw_from":49,"get_savings_withdraw_to":50,"get_state":22,"get_tags_used_by_author":5,"get_transaction":55,"get_transaction_hex":54,"get_trending_categories":23,"get_trending_tags":4,"get_withdraw_routes":47,"get_witness_by_account":67,"get_witness_count":70,"get_witness_schedule":33,"get_witnesses":66,"get_witnesses_by_vote":68,"lookup_account_names":39,"lookup_accounts":40,"lookup_witness_accounts":69,"set_block_applied_callback":2,"set_pending_transaction_callback":1,"set_subscribe_callback":0,"verify_account_authority":59,"verify_authority":58}}
    th_a  api_connection.hpp:109 call

    {"call.method":"call","call.params":["database_api","get_account_balances",["hmmmk",["GOLOS"]]]}
    th_a  websocket_api.cpp:124 on_message'}	Ditch.Core.Errors.ErrorInfo {Ditch.Core.Errors.ResponseError}
"`

Here is my code: 
`JsonRpcResponse<Asset[]> response = _operationManager
                    .GetAccountBalances(userAdress, new String[] { "GOLOS" }, CancellationToken.None);
                Asset[] assets = response.Result;

                MessageBox.Show("Balance of " + userAdress + " is " + assets[0].Value + " " + assets[0].Currency);`

**Comment by KorzunAV** [comment]
The method was removed in the blockchain (And also will be deleted from Ditch in the next version).
