### ISSUE TITLE
Assert Exception:v.is_object(): Input data have to treated as object.

### ISSUE THREAD

**Issue by petermail** [Chainers/Ditch#18]
Hi, when I invoke mehod VoteTest() from Steemit Tests project, it fails with response: _Ditch.Core.Errors.ResponseError. Code: '-32003'. Message: 'Assert Exception:v.is_object(): Input data have to treated as object.'_

Do you have any idea why is that? PostTest() returns the same response. I suspect that sent operation has wrong structure but I am not sure how to correct it. Do you know how to fix it?

**Comment by KorzunAV** [comment]
Hi! You probably try to connect to https://api.steemit.com. They start  to use new format for asset ({ "amount": "1000",  "precision": 3, "nai": "@@000000021" } instead  [ "1000", 3, "@@000000021"]). I will fix it when this format will be stabl. You may use previos version https://www.nuget.org/packages/Ditch.Steem/3.0.15 + https://www.nuget.org/packages/Ditch.Core/3.1.1  it works with hf0.19.0 and  api.steemit.com accept old requests by using Jussi (https://github.com/steemit/jussi)

**Comment by KorzunAV** [comment]
v4.0.0 adds BroadcastOperationsSynchronousLikeSteemit function to solve issues with steemit + assets accept several formats now
